### PR TITLE
Use correct version numbers for ios, android

### PR DESCRIPTION
**Pull request by ArcTanSusan**
https://github.com/cephalo-ai/pozole/issues/3545

### CODE REVIEW

**Comment by eandrejko** [comment]
CC: @ZenPylon  (?)

**Comment by ZenPylon** [comment]
@ArcTanSusan Ideally we could leave formatting as, since otherwise we'll encounter merge conflicts when merging upstream changes into our forked repo, or when submitting a PR upstream.

**Comment by ArcTanSusan** [comment]
ive un-did the formatting.

**Comment by ArcTanSusan** [comment]
I have no permissions to merge this PR, @eandrejko. Could you help me merge this?

**Pull request merged**
